backend:
  name: git-gateway
  branch: main
locale: 'es'
media_folder: "uploads/nuevas"
public_folder: "/uploads/nuevas"
collections:
  - name: "recetas"
    label: "Crear Nueva Receta"
    folder: "_recetas"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "DD/MM/YYYY", picker_utc: false}
      - {label: "Imagen destacada", name: "thumbnail", widget: "image", required: false}
      - label: "Categorías"
        name: "categories"
        widget: "select"
        multiple: true
        options:
          - { label: "Platos principales", value: "platos-principales" }
          - { label: "Ensaladas", value: "ensaladas" }
          - { label: "Desayunos", value: "desayunos-2" }
          - { label: "Postres", value: "postres" }
          - { label: "Veganas", value: "recetas-veganas" }
          - { label: "Snacks dulces", value: "snacks-2" }
          - { label: "Snacks salados", value: "snacks" }
          - { label: "Sopas y cremas", value: "sopas-y-cremas" }
          - { label: "Salsas y patés", value: "salsas" }
          - { label: "Acompañamientos", value: "acompanamientos" }
          - { label: "Olla lenta", value: "olla-lenta" }
          - { label: "Microondas", value: "microondas" }
      - {label: "Descripción corta", name: "excerpt", widget: "string"}
      - {label: "Contenido", name: "body", widget: "markdown"}
