backend:
  name: git-gateway
  branch: main
locale: 'es'
media_folder: "uploads/nuevas"
public_folder: "/uploads/nuevas"
collections:
  - name: "recetas"
    label: "Crear Nueva Receta"
    folder: "_recetas"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - label: "Título"
        name: "title"
        widget: "string"
      - label: "Fecha"
        name: "date"
        widget: "datetime"
      - label: "Imagen destacada"
        name: "thumbnail"
        widget: "image"
        media_folder: "/uploads/nuevas"
      - label: "Categorías"
        name: "categories"
        widget: "select"
        multiple: true
        options:
          - { label: "Platos principales", value: "platos-principales" }
          - { label: "Ensaladas", value: "ensaladas" }
          - { label: "Desayunos", value: "desayunos-2" }
          - { label: "Postres", value: "postres" }
          - { label: "Veganas", value: "recetas-veganas" }
          - { label: "Snacks dulces", value: "snacks-2" }
          - { label: "Snacks salados", value: "snacks" }
          - { label: "Sopas y cremas", value: "sopas-y-cremas" }
          - { label: "Salsas y patés", value: "salsas" }
          - { label: "Acompañamientos", value: "acompanamientos" }
          - { label: "Olla lenta", value: "olla-lenta" }
          - { label: "Microondas", value: "microondas" }
      - label: "Descripción"
        name: "body"
        widget: "markdown"
        hint: "Texto introductorio de la receta"
      - label: "Ingredientes"
        name: "ingredientes"
        widget: "text"
        hint: "Escribe cada ingrediente en una línea separada"
      - label: "Preparación"
        name: "preparacion"
        widget: "text"
        hint: "Escribe cada paso en una línea separada"
      - label: "Extracto"
        name: "excerpt"
        widget: "text"
        required: false
        hint: "Resumen corto para la vista previa (opcional)"
